### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by eddywashere** [rackerlabs/helix-ui#140]
Is there an example that I can checkout in a codepen or similar setup? 

Do y'all happen to have a react example as well? I can try to put that together if it doesn't exist.

**Comment by CITguy** [comment]
Currently, there's not, but that's a great suggestion. We'll put it on our list for consideration. Thanks!

**Comment by CITguy** [comment]
Work for online sandbox will be tracked via https://jira.rax.io/browse/SURF-927.

**Comment by CITguy** [comment]
Work for library-specific code examples will be tracked via https://jira.rax.io/browse/SURF-928
