### ISSUE TITLE
Button does not close popover when resized

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#145]
Regular ole' implementation of popover
Chrome: Version 64.0.3282.140 (Official Build) (64-bit) 

![resize-window](https://user-images.githubusercontent.com/5339195/36855079-4c0ad044-1d38-11e8-9522-69065ea8d7bc.gif)

**Comment by CITguy** [comment]
@jonkruse00, thanks for submitting this! We'll get it prioritized on our roadmap.

**Comment by CITguy** [comment]
Work to be tracked via https://jira.rax.io/browse/SURF-930
