### ISSUE TITLE
Feature Request: Declaring the ver. when implemented

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#148]
This is just a request that might make the website easier to read.
 
I was trying to implement `hx-modal` while on version `0.2.0` but didnt realize it wouldn't be released till `0.2.1`. 

<img width="471" alt="screen shot 2018-03-06 at 10 33 17 am" src="https://user-images.githubusercontent.com/5339195/37044724-d81d1b10-2129-11e8-974e-ae2aa8cdb2be.png">

_just a number chip/badge to the right side of Modals saying which version it is in_

**Comment by CITguy** [comment]
Thank you for the suggestion. We'll look into clarifying the minimum version in the documentation.

**Comment by CITguy** [comment]
Work will be tracked via https://jira.rax.io/browse/SURF-929
