### ISSUE TITLE
The reference to tablist in Tabset is null on switching between the page

### ISSUE THREAD

**Issue by thiagarajan-n** [rackerlabs/helix-ui#153]
https://github.com/rackerlabs/helix-ui/blob/b81abb326a9628d4c9c6159ed1b936276460a560/src/helix-ui/elements/HXTabsetElement.js#L25
The above line in HXTabsetElement will throw an error when i try switch between the page, as the constructor is not called again and the reference to tablist is null. 

We can see the same issue on 
https://github.com/rackerlabs/helix-ui/blob/b81abb326a9628d4c9c6159ed1b936276460a560/src/helix-ui/elements/HXTabsetElement.js#L33

**Comment by thiagarajan-n** [comment]
helix-ui.browser.js:2366 Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at HTMLElement.disconnectedCallback (helix-ui.browser.js:2366)

helix-ui.browser.js:2355 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLElement.connectedCallback (helix-ui.browser.js:2355)
    at appendChildToContainer (react-dom.development.js:15046)

![tablistdefect](https://user-images.githubusercontent.com/28284889/37181052-0e4f807e-22f1-11e8-9482-51628840e222.gif)

**Comment by davismartin** [comment]
Ran into the same issue opened a pull Request

**Comment by CITguy** [comment]
Fixed in #158
