### ISSUE TITLE
hx-accordion header styles subside all other header styles inside accordion stepper

### ISSUE THREAD

**Issue by thiagarajan-n** [rackerlabs/helix-ui#167]
line https://github.com/rackerlabs/helix-ui/blob/f37a9e6b772586ca562ec25abda3b0c61fe566be/src/helix-ui/styles/modules/stepper.less#L14

makes all the header to display in flex mode, thus making popover header look differently. 
<img width="533" alt="screen shot 2018-03-23 at 11 02 31 am" src="https://user-images.githubusercontent.com/28284889/37848096-e8b460b2-2ea0-11e8-9ea8-741243f63ccf.png">

instead of making them look like
<img width="375" alt="screen shot 2018-03-23 at 1 25 35 pm" src="https://user-images.githubusercontent.com/28284889/37848129-fd2c8cc2-2ea0-11e8-9a58-96d714cf5b26.png">

**Comment by CITguy** [comment]
@thiagarajan-n: Popovers were changed in v0.4.1 to use the `<hx-popover-head>` element instead of `header[slot="header"]`. Please upgrade to v0.4.1 and update your implementation of popovers.

More information can be found at https://github.com/rackerlabs/helix-ui/releases/tag/v0.4.1
