### ISSUE TITLE
BUG: Accordion CSS font inheritance flaky

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/helix-ui#169]
In certain scenarios, the font of accordion headers may not be inheriting properly.

_Font inherits as "Times" before a repaint, and "Roboto" after a repaint._
![chrome-font-repaint-bug](https://user-images.githubusercontent.com/545605/37874131-894dd6a4-2fee-11e8-8bb1-0998d5916fd6.gif)

* *NOTE:* This could very well be a Chrome rendering bug, but we should try to see if there's anything that can be done now.

**Comment by CITguy** [comment]
### Update
Tested on various browsers that natively support ShadowDOM (polyfilled browsers have #168 to worry about).

* Chrome 64/Opera 51: _No bug present_
* Chrome 65/Opera 52: _**Bug present**_
* Chrome/Chromium 66: _**Bug present**_
* Chrome Canary (67): _No bug present_
* Safari 11.0.3: _No bug present_
* Safari TP (11.2): _No bug present_

### Conclusion
Looks like a rendering bug with Blink to be corrected in a future release of Chrome. Nothing can be done at present.

**Comment by thiagarajan-n** [comment]
@CITguy There is an issue with rendering of the accordion element itself on firefox(52) version. Those accordion panel which does'nt have 'ope' attribute is completely hidden, including the header.

**Comment by CITguy** [comment]
Closing. Chrome 66 released April 17, 2018 and I'm not able to reproduce the issue any more.
