### ISSUE TITLE
Accordion step numbers missing background colors in FireFox

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#183]
Version 0.5.1 

Left-side: Firefox, Is not adding the background colors properly.
Right-side: Chrome, updates properly through each step. 

![firefox_chrome](https://user-images.githubusercontent.com/5339195/38216052-3848ffe8-368f-11e8-8fba-61c972d1bbaf.png)

**Comment by CITguy** [comment]
I'll take a look, but this is likely a CSS specificity bug with the stepper styles, due to the ShadyDOM rewrite in polyfilled browsers.
