### ISSUE TITLE
Firefox: Ignores hx-modalfoot margin

### ISSUE THREAD

**Issue by ssalinas24** [rackerlabs/helix-ui#185]
Firefox ignores the margin on hx-modalfoot. Seems like a specificity issue again after discussing with Ryan. It was mentioned that "the `hx-modal > hx-modalbody` selector breaks because ShadyDOM is inserting an extra div between them". This was seen in both FF 57 and 59. I assume probably for most of them as well.

<img width="1560" alt="screen shot 2018-03-30 at 1 52 00 pm" src="https://user-images.githubusercontent.com/14296817/38218045-1fa3289a-3696-11e8-81fa-56c05689938b.png">

I added css to override and put back the margin in Firefox for now. Its in our overrides.css file of CTUI. We can remove once we have the fix in Helix.

**Comment by CITguy** [comment]
⭐️ for @ssalinas24. Yes, it's an issue with CSS specificity + ShadowDOM rewrite.
