### ISSUE TITLE
Form Standards

### ISSUE THREAD

**Issue by EHackettTriCore** [rackerlabs/helix-ui#192]
Form and form elements need some margin/spacing concepts.

Issue 1: To wrap or not wrap input elements in a label element.

Issue 2: Forms need bottom margins so space form elements.

## Issue 1 Thoughts

The Foundation framework uses the wrapping method:

```HTML
<label>
  Input Label
  <input name="name type="text"/>
</label>
```

The Bootstap framework uses the for/id method.

```HTML
<label for="input-id">Input Label</label>
<input name="name type="text" id="input-id"/>
```

I believe MDN uses the non-wrapped method however that requires assigning wrapped form elements with an `id` attribute which also should be unique across a page. When writing compartmentalized components it can be difficult to maintain name conventions. 

E.x. you have an Organization predictive type ahead that's included in two places on the same page in different columns etc. Then you run into having a id="organization-search" or something in two places.

## Issue 2 Thoughts

Again using Foundation they have a bottom margin standard with all their text input types.
`Pro:` All forms naturally have spacing between elements under them without needing extra elements for padding.
`Con:` When you don't want a bottom margin it has to be overwritten.
![screen shot 2018-04-06 at 11 42 31 am](https://user-images.githubusercontent.com/16137890/38431025-f4e1b254-3990-11e8-9ad1-68fab5cb8619.png)

Using Bootstrap they wrap the entire label & input in an additional containing element with a class of `form-group`. 
`Pro:`: You don't have to override input elements and set their bottom margin to 0 when used not in the standard basic layout.
'Con:' You have to add an additional container around form components which creates additional stacking depths.
![screen shot 2018-04-06 at 11 42 55 am](https://user-images.githubusercontent.com/16137890/38431135-431d2ee4-3991-11e8-9fc0-17f202d71cd4.png)

Anyway the soon a standard is defined for these the better since they're relatively small concepts but if adding any kind of global margin to an input etc could require significant app reviews.

**Comment by CITguy** [comment]
Thank you for your input. We're currently prototyping form layouts and evaluating which method works best for our designs.

**Comment by CITguy** [comment]
FYI: we've found that the for/id method provides the most flexibility with regards to styling and arrangement. We'll be using this information to build out basic form control components in upcoming releases.

**Comment by CITguy** [comment]
Closing this issue. Work is being done both on Design side and Development side to define standards for Form composition.

**Comment by CITguy** [comment]
Rule of Thumb: Use `<label for="ControlID">` to apply accessible labels to form inputs and controls.
