### ISSUE TITLE
Icon scale mismatch with text

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#207]
Icon size scaling doesn't match with text.
This happens with `hx-icon` as well.
```
<h1>
  <hx-error>
    Unable to load accounts
  </hx-error>
</h1>
```
![screen shot 2018-04-25 at 9 07 52 am](https://user-images.githubusercontent.com/5339195/39251196-53b14d9a-4868-11e8-97da-89b97066c63c.png)

**Comment by CITguy** [comment]
This is an issue we are well aware of. The icon _bounding box_ is actually aligned with the text baseline, but the _visible shape_ of the icon is offset within that bounding box making it appear misaligned. As a result of this discovery, SURF-1076 was created to fix how an icon is aligned as phrasing content.
