### ISSUE TITLE
Modals do not close on `esc` and throws an error

### ISSUE THREAD

**Issue by thiagarajan-n** [rackerlabs/helix-ui#251]
https://github.com/rackerlabs/helix-ui/blob/master/src/helix-ui/elements/HXModalElement.js#L72 Close fun expects an evt and https://github.com/rackerlabs/helix-ui/blob/master/src/helix-ui/elements/HXModalElement.js#L80 is not passing any event.

Error on console
helix-ui.browser.js:3072 Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at HTMLElement._close (helix-ui.browser.js:3072)
    at HTMLElement._keyUp (helix-ui.browser.js:3080

**Comment by CITguy** [comment]
GMTA: I just discovered this today, too.

**Comment by CITguy** [comment]
Tracking work in SURF-1166
