### ISSUE TITLE
hx-ModalHead required for "close" X to work

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#252]
While making a modal we noticed that if you don't include `hx-modalhead` you will be unable to click the close 'X'. 

Css: 
```css
.pane {
 width: 450px;
}
```
<hr/>

Broken: 
```html
<hx-modal> 
  <hx-modalbody>
    <pane> ... </pan>
  </hx-modalbody>
</hx-modal>
```
![borken](https://user-images.githubusercontent.com/5339195/41373049-cb23d12c-6f14-11e8-8768-00e593f2ac2a.gif)

<hr/>

Working: 
```html
<hx-modal>
  <hx-modalhead>
    title
  </hx-modalhead>
  <hx-modalbody>
    <pane> ... </pane>
  </hx-modalbody>
</hx-modal>
```
![worky](https://user-images.githubusercontent.com/5339195/41373050-cb32f2ba-6f14-11e8-9bb6-5dbb4bc6afba.gif)

**Comment by CITguy** [comment]
@jonkruse00: Is an explicit `z-index` being applied to the pane or its contents?

@araiford or @palindromebart is: Should the "X" be able to overlap content? The specs don't explicitly mention one way or another?

**Comment by CITguy** [comment]
Seems like we need to update the Shadow DOM markup to ensure that the "X" doesn't overlap content.

**Comment by CITguy** [comment]
Closing. Captured required work in SURF-1225.
