### ISSUE TITLE
IE11 Javascript (Shadow DOM) styles breaking child globals.

### ISSUE THREAD

**Issue by EHackettTriCore** [rackerlabs/helix-ui#268]
## Describe the Bug
In IE11 any global elements like h1 - h6 or button etc are inheriting an odd font style.

## Steps to Reproduce

1. To reproduce go to your hx-modal docs example https://rackerlabs.github.io/helix-ui/components/modals/
2. Open up the modal in IE11 and you'll notice the `Demo Modal Header` is not the correct font size for an h3.

## Expected behavior
Globally styled elements like h3, paragraphs, buttons etc should retain their global font styles instead of having the `font: inherit` applied to them.

## Screenshots
 See h3 is incorrectly size at 16px (1rem) instead of 1.5rem.
<img width="1654" alt="screen shot 2018-06-28 at 2 29 48 pm" src="https://user-images.githubusercontent.com/16137890/42055194-6311bb90-7ae4-11e8-877b-73f00a969108.png">

## Environment
Please complete the following information:

 - Device: Desktop
 - OS: Windows
 - Browser: IE11
 - Version: 11.0.96

## Additional Context
This is true of any elements like buttons, paragraphs, etc that are placed inside of the modal and other custom hx elements.

**Comment by CITguy** [comment]
This may be a bug with ShadyCSS polyfill (See webcomponents/shadycss#189), as it is styled correctly in other polyfilled browsers such as Firefox and Edge.

**Comment by CITguy** [comment]
@EHackettTriCore : is this bug still present in recent releases?

**Comment by CITguy** [comment]
Closing. If this problem is still occurring, please submit a new issue.
