### ISSUE TITLE
Tooltip inside modal placement

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#298]
## Describe the Bug
Put a tooltip inside a modal

## Steps to Reproduce
Mouse of over the tooltip

## Expected behavior
Tooltip placed by cursor

## Screenshots
<img width="903" alt="screen shot 2018-08-01 at 1 06 04 pm" src="https://user-images.githubusercontent.com/35456401/43536999-11963ee0-958c-11e8-9f88-5bc877aa30fb.png">

## Environment
React 15.6, Chrome, OSX

**Comment by CITguy** [comment]
Thank you for reporting this. This is a known bug that we're aiming to fix for the v0.13.0 release.

**Comment by CITguy** [comment]
Sadly, this didn't make the v0.13.0 release. It will go out in the upcoming v0.14.0 release.

**Comment by nicko-winner** [comment]
Thanks for the update.

**Comment by CITguy** [comment]
Rather than delay the v0.14.0 release again, we cut the positioning fixes from the set of changes and will be putting full effort to get this fixed for the next release. I apologize for the delay.

**Comment by CITguy** [comment]
Should be fixed with the `v0.15.0-rc.0` release. Please verify.

**Comment by CITguy** [comment]
Confirmed behavior in https://codepen.io/CITguy/pen/wQEqqG using `helix-ui@0.15.0-rc.0`
