### ISSUE TITLE
preventDefault error on `Esc` close of SearchAssistant

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#301]
## Describe the Bug
When clearing the search and search assistant via an `esc` press we get the error message of:
```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at HTMLElement._close (helix-ui.browser.js:3072)
    at HTMLElement._keyUp (helix-ui.browser.js:3080)
```
which references the code:
```
}, {
  key: '_close',
  value: function _close(evt) {
    evt.preventDefault();

    this.open = false;
  }
}, {
```
 
- In Chrome and firefox this error is raised but continues the action (clearing the search text, assist value, etc). 

- In IE11 this error pops and stops the process immediately.

It seems `v0.12` no longer includes this `key: '_close'`

## Steps to Reproduce

1. Go to https://staging.portal.rackspace.com/tickets, you can get test credentials from QeSteve.
2. Once on the page click on the ticket search bar and go to town
3. press `ESC` and it should clear.
4. If on ff and chrome, it will clear everything.
5. If on IE11 it will clear only the search text.
6. In the console you will see the error. 

_I believe the error being thrown is preventing our code from clearing out search terms on our state_

## Expected behavior
No errors being thrown. 

## Environment
 - Reactjs
 - Helix-ui (v0.9.2)
 - Browser: Chrome(v67.0.33), Firefox(v58.0), IE11(v11.0.96)

**Comment by CITguy** [comment]
@jonkruse00: Is this still an issue? Were you able to figure out a workaround?

**Comment by CITguy** [comment]
Closing for now.
