### ISSUE TITLE
Feature Request: `relative-to` in Helix Popover

### ISSUE THREAD

**Issue by mperng** [rackerlabs/helix-ui#308]
## Problem
Apollo (account.rackspace.com) loads Helix popover elements as React components wrapping over `hx-popover` from url routes (such as `/delete-user` to load a popover with form for deleting a user). The reasons why we do loading of elements this way is because all existing legacy (canon-styled) popover code did this and because we get a React + Redux-specific benefit of not having to pass props from Redux through deep trees of nested components.

We currently use a "hack" to get the popover positioned relative to a target element when it is loaded from url: https://github.com/racker/apollo/blob/helix/app/components/helix/Popover.js#L16-L23

This temporary solution is causing unexpected behavior in different browsers. Loading a popover in Chrome works fine with this code, but loading it in Firefox causes the element to be rendered a few pixels lower on the page than expected:

### in Chrome
![screen shot 2018-08-08 at 3 08 54 pm](https://user-images.githubusercontent.com/2245612/43861614-02f6e1e6-9b1d-11e8-97b2-b6b8d984cd58.png)

### in Firefox
<img width="524" alt="screen shot 2018-08-08 at 3 08 43 pm" src="https://user-images.githubusercontent.com/2245612/43861621-08747e26-9b1d-11e8-8ab8-bc49a35380de.png">

## Proposed Solution
Add a `relative-to` attribute to `hx-popover` that works similarly to `hx-menu`'s `relative-to` attribute to allow for positioning an `hx-popover` next to an element by id (https://rackerlabs.github.io/helix-ui/elements/hx-menu/). This removes the need for the hacky code and solves the cross-browser visual issues.

## References
Slack thread containing a discussion about this feature request: https://rackspace.slack.com/archives/C1ZPBPYKZ/p1528734263000325

**Comment by CITguy** [comment]
Thank you for submitting this issue.

This work is already being tracked in SURF-1150.

**Comment by CITguy** [comment]
Fixed in #326
