### ISSUE TITLE
IE11 & Edge: tabs do not render with react router 

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#334]
## Describe the Bug
When you use react router to change to a page containing tabs, page render is halted and the page will either partially loaded or does not load at all.

## Steps to Reproduce
1.) Load this codepen in Edge: 
https://codepen.io/nicko-winner/pen/LJmBxP?editors=1010
2. Click on the Tabs link

## Expected behavior
Should see Tabs in Edge (compare with chrome or firefox)

## Environment
 - Device:  Virtual Box
 - OS: Windows
 - Browser: IE11, or Edge
 - Version: Microsoft Edge 42.17134.1.0
 - Framework: React 15.6 & React 16.4
 - React router: 2.8.1 & 4.0

**note:** IE11 does not work on code pen

## Reason for bug:
When all JS bundles are loaded and there is no wait time when switching routes: Edge and IE11, will try to render each custom element that enters the DOM from react one at time. It tries to render parent elements before there are children elements, so any code in $onConnect that is assuming child elements should exist tends to cause errors. (Tabs are the only component that had this issue that could not be worked around by simply changing the order of how the custom elements are declared.)

## Additional Context
I was able to get tabs to work by wrapping the contents of the `<tab-set />` $onConnect function in a setTimeout of 0ms. This causes $onConnect code to be run when the call stack is cleared. Maybe webcomponents have nextTick() or some other way of handling this standard way?
`setTimeout(() => {
    // contents of $connect
}, 0)`

Code pen with working edge version: https://codepen.io/nicko-winner/pen/aaGKGK

**Comment by 100stacks** [comment]
Hi @nicko-winner, this bug is captured in `SURF-1396`.
