### ISSUE TITLE
Hx-Popover positioning attribute fails to accept `bottom-left`

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#370]
## Describe the Bug
`hx-popover` positioning does not apply `bottom-left` properly

## Steps to Reproduce
1. set `hx-popover` attribute `position="bottom-left"`

## Expected behavior
To open to the "bottom-left"

## Screenshots
documentation: 
![screen shot 2018-11-01 at 2 41 09 pm](https://user-images.githubusercontent.com/5339195/47876135-85189f00-dde6-11e8-9138-32ac60b0e42c.png)

code: 
![screen shot 2018-11-01 at 2 41 02 pm](https://user-images.githubusercontent.com/5339195/47876138-88ac2600-dde6-11e8-815d-165b9f5129c2.png)

## Environment
Please complete the following information:

 - Device: Desktop
 - OS: Mac
 - Browser: chrome
 - Version: 69

**Comment by CITguy** [comment]
@jonkruse00: 

1. Is the screenshot from https://rackerlabs.github.io/helix-ui/components/popovers/ ?
2. Is the popover displaying at all?
3. Are you getting any console errors?

**Comment by CITguy** [comment]
Also, I noticed in the screenshot of your code snippet that you're using `<hx-div class="hxMd">` in JSX, but isn't `class` a reserved keyword?

**Comment by jonkruse00** [comment]
@CITguy 
1. Yes, a screenshot
2. Yes
3. Nope

JSx uses `className` but for `Helix` stuff we use a type definition file for elements 
```
interface HelixDiv extends WebComponent {
  scroll?: string;
  class?: string;
}
```

**Comment by TheNando** [comment]
I think I figured out what's going on here. The component is figuring out that it is too big to appear in the direction set and only changing it in that case. I think this is working as expected.

**Comment by CITguy** [comment]
Chatting with @TheNando, the popover seems to be working as expected, so I'm going to close this issue.
