### ISSUE TITLE
Popopver errors when entering the DOM after initial load - React

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#411]
## Describe the Bug
When a popover enters the DOM after initial load in react it, will throw an error: "Uncaught TypeError: this.getRootNode(...).getElementById is not a function"

## Steps to Reproduce

1. Go to: https://codepen.io/nicko-winner/pen/EGjEyr?editors=1010
2. Wait 5 seconds for the popover to display itself.
3. View the console, you will see an error.

## Expected behavior
Popover does not throw error when entering the DOM after initial load.

## Environment
 - Device: Desktop
 - OS: OSX
 - Browser: Chrome
 - Version: Helix RC.2

## Additional Context
if you remove the position attribute from the hx-popover and the error goes away. And Popover works as expected.

While in code pen the popover is just missing its pointer when the error occurs, in our application the popovers don't display all after getting this error.

**Comment by 100stacks** [comment]
Thank you for reporting this @nicko-winner!!! 👍 

As a result, we're conducting an extended use case audit that we'll be able to incorporate into `HelixUI`.

**Comment by EHackettTriCore** [comment]
@100stacks is the audit related to this `initialize` function feature? https://github.com/rackerlabs/helix-ui/issues/314

**Comment by 100stacks** [comment]
Closes Issue #411

**Comment by CITguy** [comment]
@nicko-winner: please verify if the latest `v0.15.0-rc.3` release has corrected this issue.

**Comment by nicko-winner** [comment]
👍👏
