### ISSUE TITLE
Positionable Elements Can Extend Off Screen

### ISSUE THREAD

**Issue by mcortez1497** [rackerlabs/helix-ui#415]
## Describe the Bug
Popovers/Menus (I think any hoverable Helix elements) that extend off of the screen do not extend the screen or reposition to be within view.

## Steps to Reproduce

1. Have a page where a hoverable element would be opened off the bottom of the screen
2. Toggle the element as open
3. Portions of the element will be unviewable, no scroll or other over available

## Expected behavior
Previous positioning behavior would ensure that the element be visible on the screen, i.e. if a popover positioned downwards extended off the bottom of the page, the toolkit repositioned it to open upwards. With the new positioning logic, I'm not sure what our expectation should be.

## Screenshots
![c33548e35a5ecad1ce3055605061d144](https://user-images.githubusercontent.com/6867918/50790153-c4021f80-1283-11e9-882a-f06bbf539e4d.gif)

## Environment
Please complete the following information:

 - Device: Laptop
 - OS: MacOS High Sierra 10.13.5
 - Browser: Chrome
 - Version: Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by 100stacks** [comment]
Thanks @mcortez1497 for submitting this issue!  We removed smart positioning with would have accounted for the previous behavior.

**Comment by CITguy** [comment]
Smart repositioning logic _will_ be reimplemented in the near future, but it likely won't be with the `0.15.0` release.
