### ISSUE TITLE
Hx-Status changes height inside a Hx-Div

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#444]
## Describe the Bug
`hx-status` has different height when used within an `hx-div` than when used outside `hx-div` even though it uses `rem` for height

## Steps to Reproduce
1. Create a `hx-panel`
2. add `hx-div` inside that panel
3. add a `hx-status` 

## Expected behavior
To remain the same slim status we all knew and loved

## Screenshots
_Left side: hx-div > hx-status_
_Right side: hx-status_
![screen shot 2019-02-05 at 4 15 59 pm](https://user-images.githubusercontent.com/5339195/52307866-6f74c180-2961-11e9-8739-0f11c128452f.png)

## Environment
Please complete the following information:

 - Device: desktop
 - OS: macky-boi
 - Browser: chrome
 - Version: 69

**Comment by CITguy** [comment]
JIRA: SURF-1568

**Comment by 100stacks** [comment]
@jonkruse00, PR #488 submitted for this bug.  The fix will be available in the `HelixUI v0.16.0` release.

Thank you for submitting! 👍

**Comment by CITguy** [comment]
Closed by #488
