### ISSUE TITLE
Icons inside of tabs causes errors

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#446]
## Describe the Bug
When clicking tooltip icon in tab user gets a console error.

## Steps to Reproduce

1. Add an icon + tooltip to a tab
2. Click the icon

## Expected behavior
No errors

## Screenshots
![2019-02-07_11-55-33](https://user-images.githubusercontent.com/35456401/52432983-ecc34200-2ad9-11e9-96d0-0f3cd18484f4.png)

related chat: https://rackspace.slack.com/archives/C1ZPBPYKZ/p1549558838021600

## Environment
 - Device: Laptop
 - OS: OSX
 - Browser: Chrome
 - Version: Latest
 - React: 15.6

## Additional Context
"This is because the tabset is listening for `click` events and setting the tab based on what was clicked. you clicked the icon, which isn't a tab, so it broke."

Note: This issues does not seem to break any existing functionality it just leaves errors in the logs.

**Comment by CITguy** [comment]
Thank you for reporting this. We have plans to refactor Tabs and this will be useful when we start that work.

**Comment by CITguy** [comment]
JIRA: SURF-1571
