### ISSUE TITLE
hx-modal close icon is forced to show at all times

### ISSUE THREAD

**Issue by ssalinas24** [rackerlabs/helix-ui#447]
## Describe the Bug
All modals are currently forced to have the `X` close icon in the top corner at all times. This includes our welcome modal (aka First time experience modal). Which isn't ideal for this case.

## Steps to Reproduce
This is currently only within our PR to update to the latest Helix 0.15.0. However, I assume it may be in staging soon, and if we compromise then it will be like this in production as well.
https://github.rackspace.com/SDP/ConsolidatedTicketingUI/pull/750

If PR is in Staging:
1. Go to 'staging.portal.rackspace.com/<account number>/tickets/list'
2. You will see our welcome modal if its your first time visiting the application within your browser
3. Else, then use the inspector developer window and click on 'Application'
4. Choose local storage and set the ctui-preferences welcome value to 'true' to see it again
5. Notice you 

## Expected behavior
Developers could benefit from either of the following:
- Have the ability to control if the close icon should be included or excluded
- Have an alternate variation of the modal that doesn't require the close icon.

### Before Helix 0.15.0:
Close Icon was in the light DOM `:before` of `hx-modalbody`.
We were able to add CSS to remove if from our first slide of the Welcome Modal. This avoided users from closing/skipping our first time experience modal before seeing the introduction of features.

<img width="1311" alt="screen shot 2019-02-07 at 1 31 24 pm" src="https://user-images.githubusercontent.com/14296817/52437725-36615c00-2add-11e9-9100-734f674d4312.png">

<img width="585" alt="screen shot 2019-02-07 at 1 27 02 pm" src="https://user-images.githubusercontent.com/14296817/52437279-29903880-2adc-11e9-833f-1cd55e42a8e3.png">

<img width="562" alt="screen shot 2019-02-07 at 1 28 23 pm" src="https://user-images.githubusercontent.com/14296817/52437330-4462ad00-2adc-11e9-9c14-bbb622c9b7d1.png">

### After Helix 0.15.0:
We don't have control of the close icon since it is now nested/controlled within some Shadow DOM.
![screen shot 2019-02-07 at 1 32 01 pm](https://user-images.githubusercontent.com/14296817/52437751-49742c00-2add-11e9-8167-c04f2d0c0917.png)

![screen shot 2019-02-07 at 1 27 53 pm](https://user-images.githubusercontent.com/14296817/52437301-3876eb00-2adc-11e9-8fbd-15d5ad71e042.png)

![screen shot 2019-02-07 at 1 18 42 pm](https://user-images.githubusercontent.com/14296817/52437205-f0f05f00-2adb-11e9-9484-85f80bb45d46.png)

## Environment
Please complete the following information:

 - Device: Desktop, but applies to all widths
 - OS: macOS High Sierra Version 10.13.6, but applies to all
 - Browser: Chrome, but applies to all.
 - Version: 71.0.3578.98

## Additional Context
Our use case at the time is for our Welcome Modal. We were previously able to override for the time being. I Imagine these type of modals could be used across customer portals more frequently once adoption spreads.

Actually it seems like our use case would fall under what the design docs deem as Educational Modals
http://helix.rax.io/components/modal.html.

**Comment by CITguy** [comment]
For reference...

### Before v0.15.0
As of `v0.14.0` (last release before `v0.15.0`), the "X" button was still in the Shadow DOM https://github.com/rackerlabs/helix-ui/blob/v0.14.0/src/helix-ui/elements/HXModalElement.html#L2-L4

### After v0.15.0
As of `v0.15.0`, the "X" button is still in the Shadow DOM.
https://github.com/rackerlabs/helix-ui/blob/v0.15.0/src/helix-ui/elements/HXModalElement.html#L3-L5

**Comment by ssalinas24** [comment]
@CITguy  this is a minor issue. I just noticed the difference as we are doing our Helix 0.15.0 update PR.

It seemed like the prior expectation was to not include a close icon upon our first time experience modal first slide. Which assures that the user at least sees the next set of instructions.
This makes sense to avoid a users habit of skipping modals and them missing some important information/instructions.

I also noticed that we have the additional documentation of Educational Modals. Located on http://helix.rax.io/components/modal.html .

The description also mentions that `Close button: For some modals, the user can click a Close button to cancel the modal.` Which lead me to believe that perhaps design would have modal cases where the close button wouldn't be desired. Such as our first slide of the first time welcome modal.

You can close this issue if it seems like its just our odd situation of overriding things prior to development, and this is actually not the desired design outcome.

**Comment by CITguy** [comment]
Closing. The Modal component is behaving as specified by the Design team. If you truly need control of the "x", please consult with Helix Design so that we can help find a suitable solution.
