### ISSUE TITLE
Tooltips take on table header styles

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#449]
## Describe the Bug
Tooltips take on table header style when they live inside the table header.

## Steps to Reproduce
1. Go to: https://codepen.io/nicko-winner/pen/YBYVJR  ,
2. Open tooltip

## Expected behavior
Tooltips should not have table heading styles such as text-transform or heavy font weights.

## Screenshots
![2019-02-07_16-35-33](https://user-images.githubusercontent.com/35456401/52444451-6d903700-2af6-11e9-82bf-81e1f131e948.png)

## Environment
 - Device:  Laptop
 - OS: OSX
 - Browser: chrome

**Comment by CITguy** [comment]
JIRA: SURF-1570
