### ISSUE TITLE
Popovers placement is off when using `relative-to`

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#450]
## Describe the Bug
Popovers placement is off when using `relative-to`

## Steps to Reproduce

1. Go to: https://codepen.io/nicko-winner/pen/qgppQq
2. Without sizing the window or scrolling notice the placement of the popover.
3. Then scroll or size window and notice that the popover placement is corrected.

## Expected behavior
Placement code should run when popover is opened.

## Screenshots
![2019-02-07_19-52-24](https://user-images.githubusercontent.com/35456401/52452647-ef418e00-2b11-11e9-8ca5-4a74b9b6be36.png)

## Environment
 - Device: desktop
 - OS:  OSX / Windows
 - Browser: chrome, IE11, Edge

## Additional Context
Inside my app when launching popovers via state changes seems to work better in chrome but placement is still off in IE / edge until the user scrolls. In this example it shows how it is broken for all browsers.

**Comment by CITguy** [comment]
Verified. Logic needs updated to set arrow position when the popover is open on render.

**Comment by CITguy** [comment]
JIRA: SURF-1572

**Comment by 100stacks** [comment]
Issue closed by PR #501.
