### ISSUE TITLE
Checkbox does not allow for an associated (clickable) label

### ISSUE THREAD

**Issue by explorigin** [rackerlabs/helix-ui#451]
## Describe the Bug
Common use-cases such as this are impossible to make the label clickable with `<hx-checkbox>`
![image](https://user-images.githubusercontent.com/697818/52487627-a6c2b880-2b83-11e9-9d02-cfa0333df53a.png)

## Steps to Reproduce
This produces the above screensnip but if you click the "Remember Me" text, it does not toggle the checkbox.
```html
<label>
  <hx-checkbox></hx-checkbox>
  Remember Me
</label>
``` 

HTML provides another way of [accomplishing this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label). Like so:

```html
<hx-checkbox id="rememberme"></hx-checkbox>
<label for="rememberme">Remember Me</label>
```
Similarly to the first example, this does not associate the label to the checkbox. I click the label and nothing happens.

## Expected behavior
Clicking labels that are associated with an <input> tag should proxy the click to its associated input tag.

## Environment
HelixUI 0.15.0 with Vue.JS
evergreen chrome on mac

**Comment by CITguy** [comment]
We are in the process of rewriting how Helix Checkboxes are built. 

We're targeting markup close to the following:

```html
<div class="hxCheckbox">
  <input type="checkbox" id="rememberme" />
  <hx-checkbox for="rememberme"></hx-checkbox>
  <label for="rememberme">Remember Me</label>
</div>
```

**Comment by CITguy** [comment]
This should now be possible with `helix-ui v0.16.0-rc.0` (https://rackerlabs.github.io/helix-ui/components/checkboxes/).
